joyfullservice/msaccess-vcs-addin

Version Control.accda.src/dbs-properties.json
Version Control.accda.src/documents.json
Version Control.accda.src/forms/frmVCSMain.bas
Version Control.accda.src/forms/frmVCSOptions.bas
Version Control.accda.src/modules/clsDbRelation.bas
Version Control.accda.src/modules/clsDbVbeProject.bas
Version Control.accda.src/modules/modAddIn.bas
Version Control.accda.src/modules/modFunctions.bas
Version Control.accda.src/modules/modImportExport.bas
Version Control.accda.src/nav-pane-groups.json
Version Control.accda.src/vbe-project.json
Version Control.accda.src/vbe-references.json
Version Control.accda.src/vcs-options.json

Use the same logic for GetCodeVBProject and GetVBProjectForCurrentDB and always return a project. I was hitting an edge case where it would fail to find the project and return nothing.
Use FSO.BuildPath to fix Log file path (remove redundant slash)
Handle HelpContextId errors, Closes #32
Use `With` pattern to automatically handle objects

Get*Project should always return something

---

.gitignore
Version Control.accda.src/dbs-properties.json
Version Control.accda.src/documents.json
Version Control.accda.src/forms/frmVCSMain.bas
Version Control.accda.src/forms/frmVCSOptions.bas
Version Control.accda.src/modules/clsDbTableData.bas
Version Control.accda.src/modules/modAddIn.bas
Version Control.accda.src/modules/modFileAccess.bas
Version Control.accda.src/modules/modFunctions.bas
Version Control.accda.src/nav-pane-groups.json
Version Control.accda.src/vbe-project.json
Version Control.accda.src/vbe-references.json
Version Control.accda.src/vcs-options.json

I have tested this round trip. I can install normally and uninstall using the new button on the settings page.
The only problem I can foresee is that there is no uninstaller for the admin installed per machine install method. The old installation will need to be manually cleaned up before you can switch to this version. Maybe we need to detect the old version and remove automatically.
Closes #25 
Closes #37

Install per user

---

Version Control.accda.src/dbs-properties.json
Version Control.accda.src/documents.json
Version Control.accda.src/modules/modFileAccess.bas
Version Control.accda.src/nav-pane-groups.json
Version Control.accda.src/vbe-project.json
Version Control.accda.src/vbe-references.json
Version Control.accda.src/vcs-options.json

Unit test for text coversions was failing with new unicode support patch. I fixed it by changing the length of a byte array that was truncating the final CRLF off the end of the file.
This now compiles on 64-bit and passes all unit tests.

PtrSafe for 64-bit

---

CONTRIBUTING.md
README.md

Now that the binary is gone from the repository, gone too is the reference to it in the README.
I noticed a link to a blank contributing guide. I provide the basic steps to get going. Understanding of Git, Github, and Access are prerequisites to understanding these steps.

Document contributing

---

Version Control.accda.src/modules/modAddIn.bas

Hello,
When developing and testing a lot of different files, it's quite a chore to reinstall the ACCDA if the version doesn't change.
With this PR, the user is asked if he wants to reinstall the ACCDE when opening it.
Saying "no" will simply open VBE as before.
This allows for:
- quick developing loop
- and user to reinstall a file maybe deleted by mistake

Ask to reinstall when opening ACCDA file

---

Version Control.accda.src/forms/frmVCSOptions.bas
Version Control.accda.src/modules/clsDbQuery.bas
Version Control.accda.src/modules/clsOptions.bas
Version Control.accda.src/modules/modFunctions.bas

Fixes #76 
As discussed, this PR adds:
- A new flag `ForceImportOriginalQuerySQL`, FALSE by default, in BUILD option tab
- If this flag is set, after importing the *.bas file, tries to open the *.sql file and set the `QueryDefs.SQL` property.
It works quite well after some testing, and no issue regarding to subqueries.

Add option to force import of original SQL for queries

---

Version Control.accda.src/forms/frmVCSOptions.bas

Fixes #85 
So I went ahead with the proposal.
**The new order is:**
1. "Other" tables (the one not represented in the DB)
This is useful to display them at the top since they are quite special
Symbol: ↪[RIGHTWARDS ARROW WITH HOOK](http://www.fileformat.info/info/unicode/char/21aa/index.htm)
1. System tables
Symbol: ⬚ [DOTTED SQUARE](http://www.fileformat.info/info/unicode/char/2b1a/index.htm)
1. Local tables
Symbol: ⊞ [SQUARED PLUS](http://www.fileformat.info/info/unicode/char/229e/index.htm)
1. Remaining tables (should be Linked table)
Symbol: 🌎 [EARTH GLOBE AMERICAS](http://www.fileformat.info/info/unicode/char/1f30e/index.htm)
**What I changed in the form:**
- In the form, I added a new column in front to hold the icon. It's easier to get back the true name, and nicer since all icons …

Sort table by type with a nice icon next to it

---

Version Control.accda.src/forms/frmVCSOptions.bas

When looking at the Testing.accdb file, I noticed the linked CSV and linked ACCDB were wrongly identified as "local".
I decided to stop using the `AllTables.Attributes` property (which is not really documented) and simply check the `TableDefs.Connect` property.
Now it works better 😸

Check TableDefs.Connect to determine if table is local

---

Version Control.accda.src/modules/clsDbHiddenAttribute.bas
Version Control.accda.src/modules/modImportExport.bas

Second try!
Fixes #91
Generates a new file `hidden-attributes.json` only if a hidden object is found:
```json
{
"Info": {
"Class": "clsDbHiddenAttribute",
"Description": "Database objects hidden attribute",
"VCS Version": "3.2.3"
},
"Items": {
"Forms": {
"Formulaire1": true
},
"Modules": {
"Classe2": true,
"Module2": true
},
"Reports": {
"Etat": true,
"Formulaire1": true
},
"Scripts": {
"Macro2": true
},
"Tables": {
"Table2": true
}
}
}
```

Export hidden attributes in hidden-attributes.json

---

Version Control.accda.src/modules/modFunctions.bas

See https://github.com/joyfullservice/msaccess-vcs-integration/commit/2c4db71665a420261f27c38e002ba8d426f3c8bd#r44408406
[Collections uses a 1-based index where arrays used a 0-based index](https://superuser.com/a/988538/1027559).
So this code throws an exception "Index out of bound"

Fix SortCollectionByValue

---

Version Control.accda.src/modules/clsDbProperty.bas

See #153
It could be possible that data (`vbBinary`) is stored in the properties of a database, e.g. LicenceKeys
With this patch it is possible to import those `vbBinary` data, with is stored in dbs-properties.json as a byte-array
Greetings
TanarRi

Add binary import in class "dbs-properties.json"

---

Version Control.accda.src/modules/modHash.bas

This hard-coded number of lines makes me feel uneasy. Although it's unlikely that you will have a module that is over 99,999 lines I think it's better to use the properties available to us to calculate the number of lines in the module. I have tested this on the test DB and my main project.

The number of lines in a CodeModule is dynamic.

---

Version Control.accda.src/modules/clsConcat.bas
Version Control.accda.src/modules/modUnitTesting.bas

At the moment there is a error in clsConcat.GetStr if the variable lngCurrentPos = 0
This will enhance the clsConcat.Selftest to raise an error.
clsConcat.GetStr has still to be fixed

Added and enhanced testing for class clsConcat

---

Version Control.accda.src/modules/modImportExport.bas

We should only rename the file if it exists.
Also log it only if we do a backup

Rename original file only if it exists

---

Version Control.accda.src/forms/frmVCSMain.bas

If the control frmVCSMain.txtDescription is selected the background will change from transparent to white.
This patch fixed it, so the background on selection is the same as the background of the form. For the user it seems the control is transparent

Fix background color of frmVCSMain.txtDescription

---

Version Control.accda.src/modules/clsLog.cls

@joyfullservice, this should just remove a single line. It isn't referred to anywhere; looks like it's a leftover or a placeholder for something that isn't there any more.

Remove excess declaration

---

Version Control.accda.src/modules/clsPerformance.cls

@joyfullservice I ... borrowed... the performance from here and one of the features we've been trying out is using the performance as a call stack manager. It seems to work pretty well, but if you forget to end an operation it can lead to a little bit of tracking down. Upside of tracking down is you ensure closing performance items when you're done. 
We also added ability to clear the performance class as a public member; but this may not be needed everywhere. 
We've been using it by not passing the log / error source along in the log (or augmenting it with the whole call stack). This way the call stack only gets checked when we care, and doesn't get asked repeatedly along the way. I haven't noticed any long-term effects yet (we've only been toying with it for a few weeks yet). One thing …

Performance Feature (CallStack!)

---

Version Control.accda.src/modules/clsLblProg.cls
Version Control.accda.src/modules/clsLog.cls

Fix bug in `clsLblProg` throws errors if you close the form before terminating the class.
Also added in patch to remove unused function `GetParentFormName`.

Updating to remove bug from closing form prior to hiding

---

Version Control.accda.src/modules/modJsonConverter.bas
Version Control.accda.src/modules/modUtcConverter.bas

In my project, I had to overhaul my time processing for various time zones. As a result, I also updated the json parser used. 
I separated out the two (they were originally two, but the upstream merged the two files) back apart to allow a smaller project that doesn't use Json to just use the time stamping functions (used largely for logging).
`modUtcConverter` is used extensively by us for time stamping, time conversion (down to millisecond accuracy, but could go lower if needed), and server communications. In this tool, it would allow the index to use a time stamp that won't be upset if your devs are in different times. 
We use a timestamp like this: dev releases version, version is timestamped in UTC. 
When a user loads the front end, it presents in local time, ensuring that they don't …

Revise json converter time

---

Wiki/Home.md

It appears as though the "Home" wiki page is a special case, where GitHub forces/redirects the user to .../repo-name/wiki instead of .../repo-name/wiki/Home. Therefore, you need to put a "wiki" prefix on all links to other pages.
This further fixes #300.

Fix broken links in Wiki Home

---

Version Control.accda.src/forms/frmVCSConflict.bas
Version Control.accda.src/forms/frmVCSConflictList.bas
Version Control.accda.src/macros/autoexec.bas

This small PR helps avoids an annoying macro error dialog from showing when running the file untrusted and improves the resolution verbiage to avoid ambiguity on the action being taken.

Improve startup and conflict verbiage

---

Version Control.accda.src/forms/frmVCSOptions.bas
Version Control.accda.src/forms/frmVCSTableData.bas
Version Control.accda.src/tbldefs/tblTableData.sql
Version Control.accda.src/tbldefs/tblTableData.xml

The table data tab uses a listbox which can be awkward to use. I also noticed there were 2 tables that were included under "Others" and that is not apparent because "Others" are hidden by default. To avoid users from overlooking, a count is provided in the filter captions. This will also show up for any hidden or system tables if there are any records for it. 
Note: the `ScaleColumn` isn't really working 100% - it has the export data as too wide. The screenshot is after me manually resizing the columns to fit. However, the subform do scale with the form so it can be as big as they like it. The issue with `ScaleColumn` probably can be addressed in a separate PR.

Convert the table data export from a listbox into a subform

---

Version Control.accda.src/forms/frmVCSInstall.bas
Version Control.accda.src/vcs-options.json

Fixes #427 
Basically updates the message box as to what needs to happen, and then opens the folder. 
The previous mechanism for detecting if it's installed was simply to see if the accde file was there or not. I didn't change any of that behavior, just updated the text and open folder.

Fixes #427 and bump version number.

---

Version Control.accda.src/modules/modSanitize.bas
Version Control.accda.src/modules/modVCSUtility.bas

Small things here & there. Detailed in the commit messages.

Misc bug fixes

---

Version Control.accda.src/dbs-properties.json
Version Control.accda.src/modules/clsOptions.cls
Version Control.accda.src/modules/clsVCSIndex.cls
Version Control.accda.src/modules/modJsonConverter.bas
Version Control.accda.src/modules/modUtcConverter.bas

Fixes #354 
Fixes #452
Bump version minor number because it's not clear that the index will allow round trip from prior types in all cases; it worked on my machine, but that may not always be the case.
The date types for the index are handled natively by `modJsonConverter` and should import/export correctly regardless of user's date / time zone or date encoding on machines.

Fixes #354 and Fixes #452

---

Version Control.accda.src/dbs-properties.json
Version Control.accda.src/modules/modUtcConverter.bas

While troubleshooting some of the performance issues in #454 and #354, I also discovered these functions could be further optimized for speed and still keep millisecond accuracy outputs are possible; this has been invaluable when troubleshooting race conditions in some of our applications (especially when using `TimeStampDate` and `ISO8601TimeStamp` for logging.
I've run this on my machine quite a few times and they're a bit faster as well. 
I also reverted back some of the name changes so the original function name is used and the "slower" version drops back when required.

Additional Optimizations for parsing time

---

Version Control.accda.src/modules/clsPerformance.cls

If a operationname has a leading space (like " MyOperation" ) the function "SortItemsByTime" fails. 
Now sorting will success.

Allow sort of operationames with leading spaces

---

Version Control.accda.src/dbs-properties.json
Version Control.accda.src/forms/frmVCSOptions.cls
Version Control.accda.src/modules/clsDbCommandBar.cls
Version Control.accda.src/modules/modSqlFunctions.bas
Version Control.accda.src/modules/modVCSUtility.bas

This enables the support for command bars import/export which was introduced a while ago but was not enabled.
Furthermore, it was throwing an error when exporting. That was due to some command bars not containing a `Picture` property and the attempt to extract the picture was not wrapped in a `CatchAny` directive, resulting in spurious error entries in the log. 
This also includes a bug fix for handling the table data in an ADP project. Because I don't think handling local table data makes sense for an ADP project, I opted to bypass the load/save which also avoids an error due to invalid reference to the `CurrentDb` in an ADP project. 
Wanted to put it out and get feedback before merging.

Enable comand bars and bug fixes

---

Version Control.accda.src/modules/modAPI.bas
Version Control.accda.src/modules/modDatabase.bas

The VBProject is currently being renamed so that Application.Run uses the correct procedure.
Alternatively, you could use the full path without file extension.
```Application.Run "c:\....\Version Control." & ProcedureName```
This variant has the advantage that it also works with a compiled add-in.
This pull request includes several changes in the `modAPI.bas` (`RunInAddIn`) and `modDatabase.bas` (`RunSubInCurrentProject`) modules. The changes focus on improving the way the add-in project name is handled and simplifying the execution of procedures.

modDatabase.RunSubInCurrentProject / modAPI.RunInAddIn: avoid rename VBProject

---

Version Control.accda.src/forms/frmVCSInstall.bas
Version Control.accda.src/forms/frmVCSInstall.cls
Version Control.accda.src/modules/modInstall.bas

Fits to discussion: Install Add-In as compiled version (accde) #435 
* frmVCSInstall.bas: 
* Added a new checkbox `chkCreateCompiledVersion` to the form, allowing users to opt for creating a compiled version of the add-in.
* modInstall.bas: 
* Modified the `InstallVCSAddin` function to include an optional parameter `blnCreateCompiledVersion`. 
* Updated the `UpdateAddInFile` function to handle the creation of a compiled version if the parameter is set.
* Added a new `CreateAccde` subroutine to generate a compiled Access file.
Form was exported with Access Version 16.0, perhaps export again with 14.0 so that the export matches the other forms.

New option in frmVCSInstall to install a compiled add-in file
