Version Control.accda.src/modules/clsDbVbeReference.bas
Version Control.accda.src/modules/modAddIn.bas
Version Control.accda.src/modules/modFileAccess.bas
Version Control.accda.src/modules/modFunctions.bas
Version Control.accda.src/modules/modImportExport.bas
Version Control.accda.src/modules/modUnitTesting.bas
Version Control.accda.src/vbe-references.json

64bit declarations for AddIn
Add UTF8 file handling using binary read/write
Change FileSystemObject to ADODB.Stream for better UTF-8 compatability
Fix incorrect procedure call in RunAfterBuild

Sort references by key name

---

Version Control.accda.src/dbs-properties.json
Version Control.accda.src/documents.json
Version Control.accda.src/forms/frmVCSOptions.bas
Version Control.accda.src/modules/clsDbProjProperty.bas
Version Control.accda.src/modules/clsDbProperty.bas
Version Control.accda.src/modules/clsDbTableData.bas
Version Control.accda.src/modules/clsDbTableDef.bas
Version Control.accda.src/modules/clsDevMode.bas
Version Control.accda.src/modules/clsLog.bas
Version Control.accda.src/modules/clsOptions.bas
Version Control.accda.src/modules/modAddIn.bas
Version Control.accda.src/modules/modEncrypt.bas
Version Control.accda.src/modules/modFileAccess.bas
Version Control.accda.src/modules/modFunctions.bas
Version Control.accda.src/modules/modImportExport.bas
Version Control.accda.src/modules/modJsonConverter.bas
Version Control.accda.src/modules/modUnitTesting.bas
Version Control.accda.src/nav-pane-groups.json
Version Control.accda.src/vbe-project.json
Version Control.accda.src/vbe-references.json
Version Control.accda.src/vcs-options.json

Replace functions with typed functions `$ for String`
Use VBNullString
Declare types, use variant if you must
Make proper test for SortDictionaryByKeys
Fix bug in SortDictionaryByKeys, passes unit test

Close Language Opportunities

---

Version Control.accda.src/dbs-properties.json
Version Control.accda.src/documents.json
Version Control.accda.src/forms/frmVCSOptions.bas
Version Control.accda.src/modules/clsDbProjProperty.bas
Version Control.accda.src/modules/clsDbProperty.bas
Version Control.accda.src/modules/clsDbTableDef.bas
Version Control.accda.src/modules/clsDbVbeReference.bas
Version Control.accda.src/modules/clsOptions.bas
Version Control.accda.src/modules/modFunctions.bas
Version Control.accda.src/nav-pane-groups.json
Version Control.accda.src/vbe-project.json
Version Control.accda.src/vbe-references.json
Version Control.accda.src/vcs-options.json

Added a dropdown box where you can select the type of security you want used on the project.

Add more options for security

---

Version Control.accda.src/modules/clsDbSavedSpec.bas
Version Control.accda.src/modules/clsDbTheme.bas
Version Control.accda.src/modules/clsOptions.bas
Version Control.accda.src/modules/modEncrypt.bas
Version Control.accda.src/modules/modFileAccess.bas
Version Control.accda.src/modules/modFunctions.bas
Version Control.accda.src/modules/modUnitTesting.bas

Add `SecureBetween` in same manner as `Secure` and `SecurePath`
Add `SaveToFile` during export of __clsDbTheme__
Add `ClearOrphanedSourceFolders` function for __clsDbTheme__
Add `DefaultKeyName` constant to __modEncrypt__

clsDbTheme changes and other small suggestions

---

Version Control.accda.src/modules/clsDbVbeReference.bas
Version Control.accda.src/vbe-references.json

Fixes #97 
I reverted the commit which removed reference version and simply added an error handling.

Fix VBE reference import/export

---

Version Control.accda.src/modules/modJsonConverter.bas

per #103, add option private module to JSON

Add option private module to JSON module

---

Version Control.accda.src/modules/modAPI.bas
Version Control.accda.src/modules/modAddIn.bas

Initial version for modAPI to expose commands to referencing database for #117.

#117: Add modAPI to expose selected functions

---

Version Control.accda.src/modules/clsDbForm.bas
Version Control.accda.src/modules/clsDbReport.bas
Version Control.accda.src/modules/modFunctions.bas

Add Form Print settings for form config.

Initial form Print Settings export for #115

---

Version Control.accda.src/modules/modFunctions.bas

Handle UNC paths

---

Version Control.accda.src/modules/modFileAccess.bas

@A9G-Data-Droid I took the liberty of copying your code and applying it to dev.

Copy from A9G-Data-Droid and put on dev branch.

---

Version Control.accda.src/modules/modHash.bas

#130 initial PR; please test out and see if this works.

initial conversion of hashing functions to remove dependancy on .Net

---

Version Control.accda.src/modules/modHash.bas

Fixes #136 and adds error logging to hash routines (which, we probably want to know if there's an error on hash).

Fixes #136 and adds error logging to hash routines 

---

Version Control.accda.src/modules/clsDevMode.bas

#115 Fix and moves prtMip to correct location.

Prt mip update

---

Version Control.accda.src/forms/frmVCSOptions.bas
Version Control.accda.src/modules/clsOptions.bas
Version Control.accda.src/modules/modImportExport.bas
Version Control.accda.src/vcs-options.json

Adding option to turn off the legacy prompt.

Adding options for #148 and button.

---

Version Control.accda.src/forms/frmVCSMain.bas
Version Control.accda.src/modules/modAddIn.bas
Version Control.accda.src/modules/modInstall.bas

For #157, this changes export behavior and autocloses form; also adds in ability to go right to settings from the "ribbon".

improveExportsource and enable simplified ribbon handling.

---

Version Control.accda.src/forms/frmVCSInstall.bas
Version Control.accda.src/modules/modInstall.bas

defaulted to current settings; saves info in registry for future use.

adding ability to save the trusted settings;

---

Version Control.accda.src/modules/clsLblProg.bas

Small typo

---

.gitignore
Version Control.accda.src/modules/clsDbTheme.bas
Version Control.accda.src/modules/modHash.bas
Version Control.accda.src/modules/modImportExport.bas

Fix theme import and add logging to import/export routines to aid finding errors or issues.

Fix theme import

---

Version Control.accda.src/modules/clsDevMode.bas

Fixes Joyfullservice#175 and adds logging to clsDevMode
(Initial PR only includes logging to sniff out issues)
@joyfullservice, I've made this editable by maintainers, feel free to commit to this to troubleshoot anything.

Fixes joyfullservice#175

---

Version Control.accda.src/modules/clsConcat.bas
Version Control.accda.src/modules/modUnitTesting.bas

clsConcat.bas fix #194

---

Version Control.accda.src/modules/clsLog.bas

We had to use the Textbox which is setted from the calling form

Don't use hardcoded textbox

---

Version Control.accda.src/dbs-properties.json
Version Control.accda.src/modules/clsPerformance.bas
Version Control.accda.src/modules/clsPerformanceItem.bas
Version Control.accda.src/modules/modUnitTesting.bas

Adding indentations of operations depending on their level to function "GetReports"
Also includes TestMethod "clsPerformanceLevel"

Adding indentations to clsPerformance

---

Testing/Testing.accdb.src/vbe-project.json
Testing/Testing.accdb.src/vcs-options.json
Version Control.accda.src/modules/clsDbVbeProject.bas

This will do the same validation on Export that was written for Import.
See discussion on #197

Refactor help property validation

---

Version Control.accda.src/modules/clsOptions.bas

Table names are not case-sensitive when exported

---

Version Control.accda.src/dbs-properties.json
Version Control.accda.src/forms/frmVCSOptions.bas
Version Control.accda.src/modules/clsOptions.cls
Version Control.accda.src/modules/modAPI.bas
Version Control.accda.src/modules/modConstants.bas
Version Control.accda.src/modules/modSanitize.bas
Version Control.accda.src/vcs-options.json

Initial definition of sanitize levels.

---

Version Control.accda.src/modules/modAddIn.bas

make it easier to increase build numbers when deploying

Make it easier to bump builds.

---

Version Control.accda.src/dbs-properties.json
Version Control.accda.src/modules/clsOptions.cls
Version Control.accda.src/vbe-project.json
Wiki/Documentation.md
Wiki/Editing-and-Contributing.md
Wiki/Home.md
Wiki/Installation.md
Wiki/Options.md
Wiki/Supported-Objects.md

Made some more wiki updates and consistency changes, as well as hopefully improved readability. 
Removed some extra entries that were duplicated or are no longer present.

Wiki updates

---

Version Control.accda.src/dbs-properties.json
Version Control.accda.src/forms/frmVCSMain.bas

Fixes #291 
It works on my end; can someone else test it, too?

Removing separate handling of close form.

---

Version Control.accda.src/dbs-properties.json
Version Control.accda.src/forms/frmVCSMain.bas

Fixes #291 on master

---

Version Control.accda.src/modules/clsPerformance.cls

ensure all relevant items are reset in call stack

---

Version Control.accda.src/modules/clsLblProg.cls

Updates to clsLblProg based on additional discussions and tweaking.

Cls lbl prog fix v2

---

Version Control.accda.src/modules/clsDbConnection.cls
Version Control.accda.src/modules/clsDbQuery.cls
Version Control.accda.src/modules/clsDbSharedImage.cls
Version Control.accda.src/modules/clsDbTableDef.cls
Version Control.accda.src/modules/modSanitize.bas

Various Bug fixes

---

Version Control.accda.src/modules/modFunctions.bas

It should be LongPtr instead of Long

Use LongPtr according to declaration

---

Version Control.accda.src/modules/modAPI.bas

Prevent re-entry due to user accidentally double-clicking a button which would then cause errors with operations that are not generally re-entrant, particularly with import/export operations.
Normally, we prevent this problem by disabling the button at the start of routine then re-enabling it at end of routine but that is not a good solution in this case for two reasons:
1) If the user is impatient and twitchy enough, the user can click two adjacent buttons rapidly and still run into problems especially if the buttons' operations aren't re-entrant.
2) IIUC, `Application.Run` returns immediately and will not wait on the code to finish running. Therefore, the button would be re-enabled too soon and we still would have re-entrancy problems. 
To handle this, we use a static variable that is …

Prevent re-entrancy on ribbon commands.

---

Version Control.accda.src/modules/clsDbTheme.cls

AlternatePath was not taken into account

Fix export of Theme File

---

Version Control.accda.src/forms/frmVCSMain.bas
Version Control.accda.src/modules/clsDbQuery.cls
Version Control.accda.src/modules/clsSqlFormatter.cls

More bug fixes. See commit comments.

Misc bug fixes

---

Version Control.accda.src/modules/modErrorHandling.bas

I found a (probably one off) incident where `LogUnhandledErrors` causes a race condition. I also made it so it's not dependent on external flags, and will run whether or not the log is setup. 
I added a testing function to validate it works with or without the log or other things setup before running, and an example of how to use `LogUnhandledErrors` with a referenced calling function to give some breadcrumbs.

Fix issue with LogUnhandledErrors and simplify use.

---

Version Control.accda.src/modules/clsPerformance.cls

replace VBA commands:
format with format$
trim with trim$

Implement correction according to rubberduck

---

Version Control.accda.src/dbs-properties.json
Version Control.accda.src/modules/clsDbProperty.cls

This is a potential fix for #459

Addresses #459

---

Version Control.accda.src/dbs-properties.json
Version Control.accda.src/modules/clsViewDiff.cls

Fixes #502 corrects use of Environ variable without use of dirctory traversal keys. Bumps version.

Fixes #502

---

Version Control.accda.src/modules/clsPerformance.cls

This fix was suggested by Rubberduck

Add missing Getter for DigitsAfterDecimal

---

Version Control.accda.src/modules/clsVersionControl.cls
Version Control.accda.src/modules/modUIAutomation.bas

Fixes #590 
I modified so the checks use the same approach (`LikeAny`) for each type of item.
I also took the liberty to modify the warning displayed when no item is found so a future user will be able to quickly understand the issue.
Example:

modUIAutomation: add support for French language
